name: "ensemble-model"
platform: "ensemble"

input [
    {
        name: "ensemble:in:jpg"
        data_type: TYPE_UINT8
        dims: [ -1, -1 ]
    }
]

output [
    {
        name: "ensemble:scores:tensor"
        data_type: TYPE_FP32
        dims: [ -1 ]
    },
    {
        name: "ensemble:labels:tensor"
        data_type: TYPE_FP32
        dims: [ -1 ]
    },
    {
        name: "ensemble:boxes:tensor"
        data_type: TYPE_FP32
        dims: [ -1, 4 ]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "ensemble-step1-preproc"
            model_version: -1
            input_map {
                key:    "in:jpg"                # Model 1's input Tensor
                value:  "ensemble:in:jpg"       # this is the name of the ensemble's input
            },
            output_map {
                key:    "out:tensor"
                value:  "preproc_to_inference_input"
            }
        },
        {
            model_name: "ensemble-step2-inference"
            model_version: -1
            input_map {
                key:    "input"
                value:  "preproc_to_inference_input"
            },
            output_map {
                key:    "dets"
                value:  "dets_to_postproc"
            },
            output_map {
                key:    "labels"
                value:  "labels_to_postproc"
            }
        },
        {
            model_name: "ensemble-step3-postproc"
            model_version: -1
            input_map {
                key:    "dets:postproc"
                value:  "dets_to_postproc"
            },
            input_map {
                key:    "labels:postproc"
                value:  "labels_to_postproc"
            },
            output_map {
                key:    "scores:tensor"
                value:  "ensemble:scores:tensor"
            },
            output_map {
                key:    "labels:tensor"
                value:  "ensemble:labels:tensor"
            },
            output_map {
                key:    "boxes:tensor"
                value:  "ensemble:boxes:tensor"
            }
        }
    ]
}